import Link from 'next/link'
import { ChevronLeft } from 'lucide-react'

export const metadata = {
  title: 'Terms of Service — FitMind AI',
  description: 'Terms and conditions for using FitMind AI.',
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-10">
      <Link href="/" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground mb-8">
        <ChevronLeft className="h-4 w-4" /> Back
      </Link>

      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-10">Last updated: May 2025</p>

      <div className="prose prose-sm dark:prose-invert max-w-none space-y-8 text-foreground">

        <section>
          <h2 className="text-lg font-semibold mb-3">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            By creating an account or using FitMind AI, you agree to these Terms of Service. If you do not agree, do not use the app. These terms apply to all users, including free and Pro subscribers.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">2. Not Medical Advice</h2>
          <div className="rounded-xl bg-orange-50 dark:bg-orange-950/30 border border-orange-200 dark:border-orange-900/40 p-4 mb-3">
            <p className="text-sm font-semibold text-orange-700 dark:text-orange-400">⚠️ Important Health Disclaimer</p>
            <p className="text-sm text-orange-700/80 dark:text-orange-400/80 mt-1">
              FitMind AI is a fitness and wellness tool — not a medical system. Nothing in this app constitutes medical advice, diagnosis, or treatment.
            </p>
          </div>
          <p className="text-muted-foreground leading-relaxed">
            Always consult a qualified healthcare professional before starting any new exercise or diet programme, especially if you have any medical conditions, injuries, or take medication. Do not disregard professional medical advice because of something you read or receive in this app.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">3. Your Account</h2>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground leading-relaxed">
            <li>You must be at least 16 years old to use FitMind AI</li>
            <li>You are responsible for keeping your account secure</li>
            <li>You must provide accurate information — inaccurate data leads to poor AI recommendations</li>
            <li>One account per person. Do not share accounts</li>
            <li>We reserve the right to suspend accounts that violate these terms</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">4. Free and Pro Plans</h2>
          <p className="text-muted-foreground leading-relaxed">
            FitMind AI offers a free tier and a Pro subscription (₹499/month). The free tier includes core features with limited AI personalisation. Pro includes full AI-generated plans, advanced insights, and priority features.
          </p>
          <p className="text-muted-foreground leading-relaxed mt-2">
            Subscriptions are billed monthly via Razorpay. You can cancel at any time — your Pro access continues until the end of the billing period. We do not offer refunds for partial months.
          </p>
          <p className="text-muted-foreground leading-relaxed mt-2">
            We reserve the right to change pricing with 30 days notice to existing subscribers.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">5. AI-Generated Content</h2>
          <p className="text-muted-foreground leading-relaxed">
            Workout plans, meal suggestions, and coaching responses are generated by AI models. While we design prompts to be safe and accurate, AI can make mistakes. Always apply your own judgement.
          </p>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground leading-relaxed mt-2">
            <li>Do not follow any AI suggestion that causes pain, discomfort, or distress</li>
            <li>Calorie and macro estimates are approximations, not exact values</li>
            <li>The AI coach is not a substitute for a certified personal trainer or dietitian</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">6. Acceptable Use</h2>
          <p className="text-muted-foreground leading-relaxed">You agree not to:</p>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground leading-relaxed mt-2">
            <li>Use the app for any unlawful purpose</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the API</li>
            <li>Share your account or resell access</li>
            <li>Input false information to manipulate AI recommendations</li>
            <li>Use the app to harm yourself or others</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">7. Your Data</h2>
          <p className="text-muted-foreground leading-relaxed">
            You own your data. We process it to provide the service. See our <Link href="/privacy" className="text-orange-500 hover:underline">Privacy Policy</Link> for full details on how we collect, store, and use your information.
          </p>
          <p className="text-muted-foreground leading-relaxed mt-2">
            You can export all your data at any time from the Export page. You can request deletion by contacting us.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">8. Referral Programme</h2>
          <p className="text-muted-foreground leading-relaxed">
            The referral programme grants 7 days of Pro access to both referrer and referee when a new user signs up via a valid referral link. Referral rewards have no cash value and cannot be transferred or exchanged. We reserve the right to modify or end the referral programme at any time.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">9. Limitation of Liability</h2>
          <p className="text-muted-foreground leading-relaxed">
            FitMind AI is provided "as is" without warranties of any kind. We are not liable for any injury, health outcome, financial loss, or other damage resulting from your use of the app or reliance on AI-generated content.
          </p>
          <p className="text-muted-foreground leading-relaxed mt-2">
            Our total liability to you for any claim is limited to the amount you paid us in the 3 months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">10. Termination</h2>
          <p className="text-muted-foreground leading-relaxed">
            You may delete your account at any time. We may suspend or terminate accounts that violate these terms. On termination, your data is deleted within 30 days.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">11. Governing Law</h2>
          <p className="text-muted-foreground leading-relaxed">
            These terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of India.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">12. Contact</h2>
          <p className="text-muted-foreground leading-relaxed">
            For questions about these terms:<br />
            <strong className="text-foreground">aifitness034@gmail.com</strong>
          </p>
        </section>

      </div>

      <div className="mt-12 pt-8 border-t text-sm text-muted-foreground flex gap-6">
        <Link href="/privacy" className="hover:text-foreground">Privacy Policy</Link>
        <Link href="/" className="hover:text-foreground">Back to Home</Link>
      </div>
    </div>
  )
}
